name: Doc
on:
  push:
    branches: [ master ]

jobs:
  doc-build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Prepare
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-sphinx
    - name: Build
      run: |
        cd doc
        make html
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: doc/_build/html
        clean: true
        token: ${{ secrets.GITHUB_TOKEN }}
